---
name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "Triage"]
assignees: ["manchuck", "pardel", "dragonmantank"]
body:
 - type: dropdown
   id: node_version
   attributes:
    label: Node Version
    description: What version of NodeJS are you using?
    options:
     - 16.x
     - 18.x
     - 20.x
     - 21.x
   validations:
    required: true
 - type: dropdown
   id: platform
   attributes:
    label: Platform
    description: What is the platform you are having the issue on?
    multiple: true
    options:
     - "Windows"
     - "Linux"
     - "Mac (intel)"
     - "Mac (Apple Silcon)"
     - "Docker Container"
   validations:
    required: true
 - type: input
   id: sdk_version
   attributes:
    label: SDK Version
    description: What version of the SDK are you using?
    placeholder: 3.10.0
   validations:
    required: true
 - type: textarea
   id: code_sample
   attributes:
    label: Code Sample
    description: Please provide a sample of the code
   validations:
    required: true
 - type: textarea
   id: expected_behavior
   attributes:
    label: Expected Behavior
    description: Please provide a brief description of what you wanted to
      happen
   validations:
    required: true
 - type: textarea
   id: actual_behavior
   attributes:
    label: Actual Behavior
    description: Please provide a brief description of what happened
   validations:
    required: true
