export enum GenericErrors {
    LOW_BALANCE = 'low-balance',
    UNAUTHORIZED = 'unauthorized',
    FORBIDDEN = 'forbidden',
    NOT_FOUND = 'not-found',
    UNPROVISIONED = 'unprovisioned',
    ACCOUNT_SUSPENDED = 'account-suspended',
    JWT_EXPIRED = 'jwt-expired',
    JWT_REVOKED = 'jwt-revoked',
    INVALID_API_KEY = 'invalid-api-key',
    INVALID_SIGNATURE = 'invalid-signature',
    INVALID_IP = 'invalid-ip',
    MULTIPLE_AUTH_METHODS = 'multiple-auth-methods',
    INVALID_ID = 'invalid-id',
    INVALID_JSON = 'invalid-json',
    WRONG_VERB = 'wrong-verb',
    ACCEPT_HEADER = 'accept-header',
    CONTENT_TYPE_HEADER = 'content-type-header',
    UNAVAILABLE_LEGAL = 'unavailable-legal',
    APPLICATION_SUSPENDED = 'application-suspended',
}
