name: Build Wiki

on:
  workflow_run:
    workflows:
      - 'Release Action'
  workflow_dispatch:

permissions: read-all

jobs:
  build-wiki-documentation:
    name: Build Wiki Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Set up Node.js
        uses: actions/setup-node@65d868f8d4d85d7d4abb7de0875cde3fcc8798f5
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Generate JSDoc documentation
        run: |
          npx jsdoc-to-markdown --files 'packages/*/lib/**/*.js' > docs/API.md
          node scripts/generateExample.mjs
          cp EXAMPLES.md docs/EXAMPLES.md

      - name: Sync Wiki to Docs
        uses: newrelic/wiki-sync-action@8fb7a9efe4e975bdb2977107fbed96fa0433db52
        with:
          source: docs
          destination: wiki
          token: ${{ secrets.WIKI_TOKEN }}
          gitAuthorName: VonageDevRel
          gitAuthorEmail: DevRel@vonage.com
          branch: main

